version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: bookshelf-elder-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookshelf-elder
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - bookshelf-elder-network

volumes:
  pgdata:
